import type { Metadata } from "next";
import "@/styles/globals.css";
import ReactQueryProvider from "@/store/ReactQueryProvider";

export const metadata: Metadata = {
  title: "DropTheWave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
